name: 'Actions for Discord'
description: 'Outputs a message to Discord.'
author: step-security
branding:
  icon: message-square
  color: gray-dark
inputs:
  args:
    description: 'The message to display in the Discord message.'
    required: true
  # TODO: Handle configuration through Action inputs.
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/action-discord:v0.4.0@sha256:52f5f2081b9b0e44c1e657e0e7f639708d5b843a7108b55a05e03018f5ba1b30' #v0.4.0
