name: 'Actions for Discord'
description: 'Outputs a message to Discord.'
author: step-security
branding:
  icon: message-square
  color: gray-dark
inputs:
  args:
    description: 'The message to display in the Discord message.'
    required: true
  # TODO: Handle configuration through Action inputs.
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/action-discord:v0.1.3@sha256:962b369d3a81f330bf0b4d06c9db58eaa04595f2ba78d38533445c2df256ec31' #v0.1.3
