name: 'Actions for Discord'
description: 'Outputs a message to Discord.'
author: step-security
branding:
  icon: message-square
  color: gray-dark
inputs:
  args:
    description: 'The message to display in the Discord message.'
    required: true
  # TODO: Handle configuration through Action inputs.
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/action-discord:v0.1.5@sha256:d44f7524e4e197be62d327b48f0d9c84e1bee65f977352b0276220e053f727bf' #v0.1.5
